### PR TITLE
Installation instructions

### PR DESCRIPTION
**Pull request by ondrejmirtes**
Hi,
phpstan/extension-installer is completely optional. Your README should still contain instructions on how to get going.

As for your question:

> Question is there a way for an extension to plug into broker->hasClass() for dynamically created classes?

What is "dynamically created class"?

### CODE REVIEW

**Comment by fooman** [comment]
@ondrejmirtes thanks for stopping by.  I did make the use of the extension-install non-optional https://github.com/fooman/phpstan-magento2-magic-methods/blob/master/composer.json#L14

> What is "dynamically created class"?

The Magento 2 framework generates some classes on the fly (or pre-generates them during a compilation step). There are a few different types it does this for and might be best explained via one example.

Appending the name Factory to the class name will auto generate a factory for this class (if it doesn't have a pre-existing factory).

So using `\Magento\Directory\Model\CountryFactory`
would dynamically create the class
`\Magento\Directory\Model\CountryFactory` which would provide instances of `\Magento\Directory\Model\Country` via the method `\Magento\Directory\Model\CountryFactory::create()`

However this autogeneration behaviour only kicks in when the full framework is loaded. I was thinking I could provide an extension that matches on class names ending in Factory, the method `create()` that would be used from the factory would return the class. 

I am currently using what Magento 2 is using themselves during their [unit tests](https://github.com/fooman/phpstan-magento2-magic-methods/blob/master/bootstrap.php) but the generated classes from this do not fully match what the actual framework does (it only creates stubs for the methods but does not return the actual class).

**Comment by ondrejmirtes** [comment]
Well, you should remove the requirement for extension-installer because some might not want it.

**Comment by ondrejmirtes** [comment]
This sounds like you should hook the magic generating autoloader in the PHPStan autoloader chain. It might already be solved here: https://github.com/bitExpert/phpstan-magento

**Comment by fooman** [comment]
Thanks hadn't yet seen that project. Will check that out, but looks like they figured out a few more things than me so might just archive this one.

**Comment by convenient** [comment]
Hello

Just a note that the hard requiring of `phpstan/extension-installer` caught me for a bit this morning.

Part of our CI pipeline ran `composer install --no-scripts` which meant this module was not loaded. We run with `--no-scripts` in this instance because there are some large scripts, and this section of the pipeline was meant for a quick static analysis check so didn't want to slow them down.

I did the manual include of the extension in `phpstan.neon` which allowed CI to work but it broke it for the developers local machine as when they ran a plain old `composer install` it would include this module twice and error with `This file is included multiple times`

```
includes:
        - vendor/fooman/phpstan-magento2-magic-methods/extension.neon
```

I have fixed this for us by maintaining the file include in `phpstan.neon` and adding this to my composer.json to clobber `phpstan/extension-installer`

```json
    "replace": {
        "phpstan/extension-installer": "*"
    },
```

**Comment by ondrejmirtes** [comment]
Yes, requiring `phpstan/extension-installer` in an extension is being a bad citizen of the ecosystem. The extension-installer is intentionally designed only for "happy path" users, it does not cater to everyone's needs. For example, if you only want to use a few select rules from phpstan-strict-rules, you can't use extension-installer.

**Comment by fooman** [comment]
Okay seeing that me sharing my happy path approach is frowned upon I will make this repo private soon as to not be a bad citizen. The alternative would mean manually changing all our repositories on my end which I am not prepared to do.

**Comment by convenient** [comment]
@fooman Please don't make this private! It's a good repo I was just sharing a workaround for the hard requirement.

**Comment by ondrejmirtes** [comment]
@fooman Using your extension means that more people can't use other extensions. You should require `extension-installer` in your own projects instead.

@convenient You're free to fork it and make it usable to more people :)

**Comment by fooman** [comment]
okay I have added a call-out to the readme with @convenient's suggestion of undoing the installer. 

@ondrejmirtes maybe your concerns for users with more advanced needs can be alleviated by adding an extension override mechanism in one's project to the installer, ie

```
excludes:
    - vendor/fooman/phpstan-magento2-magic-methods/extension.neon
```

**Pull request closed without merging**
